<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net7.0</TargetFramework>
    <DebugType>portable</DebugType>
    <Title>XrmMockup365</Title>
  </PropertyGroup>
  <PropertyGroup>
    <PackageProjectUrl>https://github.com/MattTrinder1/XrmMockup</PackageProjectUrl>
    <Authors>Matt Trinder (Tisski), Delegate A/S, Martin Kasban Tange, Magnus Gether Sørensen</Authors>
    <Company>Delegate</Company>
    <Description>Bleeding edge version of Delegate A/S XrmMockup</Description>
    <PackageTags>dynamics-365 dynamics-crm csharp testing unit-testing mockup simulation-engine</PackageTags>
    <Copyright>Copyright (c) Delegate A/S 2017</Copyright>
    <PackageIcon>XrmMockup-sticker_small.png</PackageIcon>
    <RepositoryUrl>https://github.com/MattTrinder1/XrmMockup</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <Version>1.0.12</Version>
    <Product>BleedingEdgeXrmMockup365</Product>
    <PackageId>BleedingEdgeXrmMockup365</PackageId>
    <AssemblyVersion>1.0.12.0</AssemblyVersion>
    <FileVersion>1.0.12.0</FileVersion>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>TRACE;DEBUG;XRM_MOCKUP_365</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE;XRM_MOCKUP_365</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="..\MetadataGen\MetadataGenerator365\bin\Release\$(TargetFramework)\MetadataGenerator365.exe" Pack="true" PackagePath="content\net462\Metadata" />
    <Content Include="..\MetadataGen\MetadataGenerator365\bin\Release\$(TargetFramework)\MetadataGenerator365.exe.config" Pack="true" PackagePath="content\net462\Metadata" />
    <Content Include="..\MetadataGen\MetadataGenerator365\bin\Release\$(TargetFramework)\Microsoft.Crm.Sdk.Proxy.dll" Pack="true" PackagePath="content\net462\Metadata" />
    <Content Include="..\MetadataGen\MetadataGenerator365\bin\Release\$(TargetFramework)\Microsoft.IdentityModel.Clients.ActiveDirectory.dll" Pack="true" PackagePath="content\net462\Metadata" />
    <Content Include="..\MetadataGen\MetadataGenerator365\bin\Release\$(TargetFramework)\Microsoft.IdentityModel.Clients.ActiveDirectory.Platform.dll" Pack="true" PackagePath="content\net462\Metadata" />
    <Content Include="..\MetadataGen\MetadataGenerator365\bin\Release\$(TargetFramework)\Microsoft.Rest.ClientRuntime.dll" Pack="true" PackagePath="content\net462\Metadata" />
    <Content Include="..\MetadataGen\MetadataGenerator365\bin\Release\$(TargetFramework)\Microsoft.Xrm.Sdk.Deployment.dll" Pack="true" PackagePath="content\net462\Metadata" />
    <Content Include="..\MetadataGen\MetadataGenerator365\bin\Release\$(TargetFramework)\Microsoft.Xrm.Sdk.dll" Pack="true" PackagePath="content\net462\Metadata" />
    <Content Include="..\MetadataGen\MetadataGenerator365\bin\Release\$(TargetFramework)\Microsoft.Xrm.Sdk.Workflow.dll" Pack="true" PackagePath="content\net462\Metadata" />
    <Content Include="..\MetadataGen\MetadataGenerator365\bin\Release\$(TargetFramework)\Microsoft.Xrm.Tooling.Connector.dll" Pack="true" PackagePath="content\net462\Metadata" />
    <Content Include="..\MetadataGen\MetadataGenerator365\bin\Release\$(TargetFramework)\Newtonsoft.Json.dll" Pack="true" PackagePath="content\net462\Metadata" />
    <Content Include="..\..\files\TypeDeclarations.cs" Pack="true" PackagePath="content\net462\Metadata" />
    <None Include="..\..\resources\XrmMockup-sticker_small.png" Pack="true" PackagePath="" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CrmSdk.Workflow" Version="9.0.2.49" />
    <PackageReference Include="Microsoft.PowerPlatform.Dataverse.Client" Version="1.1.9" />
    <PackageReference Include="UiPath.Workflow.Runtime" Version="6.0.3" />
  </ItemGroup>
  <Import Project="..\XrmMockupShared\XrmMockupShared.projitems" Label="Shared" />
  <Import Project="..\XrmMockupWorkflow\XrmMockupWorkflow.projitems" Label="Shared" />
  <Import Project="..\MetadataSkeleton\MetadataSkeleton.projitems" Label="Shared" />
</Project>