<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <DebugType>portable</DebugType>
    <Title>XrmMockup365Test</Title>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <ErrorReport>prompt</ErrorReport>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <ErrorReport>prompt</ErrorReport>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\XrmMockup365\XrmMockup365.csproj" />
    <ProjectReference Include="..\TestPluginAssembly365\TestPluginAssembly365.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CrmSdk.Workflow" Version="9.0.2.49" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.7.1" />
    <PackageReference Include="Microsoft.PowerPlatform.Dataverse.Client" Version="1.1.9" />
    <PackageReference Include="UiPath.Workflow.Runtime" Version="6.0.3" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.ServiceModel.Primitives" Version="6.0.0" />
    <PackageReference Include="System.ServiceModel.Http" Version="6.0.0" />
    <PackageReference Include="System.ServiceModel.Duplex" Version="6.0.0" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="6.0.0" />
    <PackageReference Include="System.ServiceModel.Security" Version="6.0.0" />
    <PackageReference Include="System.ServiceModel.Federation" Version="6.0.0" />
  </ItemGroup>
  <Import Project="..\SharedTests\SharedTests.projitems" Label="Shared" />
</Project>