<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net7.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Daxif\bin\Delegate.Daxif.dll" />
    <Content Include="Daxif\bin\Delegate.Daxif.pdb" />
    <Content Include="Daxif\bin\Delegate.Daxif.xml" />
    <Content Include="Daxif\bin\FSharp.Core.dll" />
    <Content Include="Daxif\bin\Microsoft.ApplicationInsights.dll" />
    <Content Include="Daxif\bin\Microsoft.Crm.Sdk.Proxy.dll" />
    <Content Include="Daxif\bin\Microsoft.Crm.Services.Utility.dll" />
    <Content Include="Daxif\bin\Microsoft.IdentityModel.Clients.ActiveDirectory.dll" />
    <Content Include="Daxif\bin\Microsoft.IdentityModel.Clients.ActiveDirectory.Platform.dll" />
    <Content Include="Daxif\bin\microsoft.identitymodel.dll" />
    <Content Include="Daxif\bin\Microsoft.PowerApps.AppInsights.BatchedTelemetry.dll" />
    <Content Include="Daxif\bin\Microsoft.PowerApps.AppInsights.BatchedTelemetryChannel.dll" />
    <Content Include="Daxif\bin\Microsoft.Rest.ClientRuntime.dll" />
    <Content Include="Daxif\bin\Microsoft.Xrm.Sdk.Deployment.dll" />
    <Content Include="Daxif\bin\Microsoft.Xrm.Sdk.dll" />
    <Content Include="Daxif\bin\Microsoft.Xrm.Sdk.Workflow.dll" />
    <Content Include="Daxif\bin\Microsoft.Xrm.Tooling.Connector.dll" />
    <Content Include="Daxif\bin\Newtonsoft.Json.dll" />
    <Content Include="Daxif\bin\SolutionPackager.exe" />
    <Content Include="Daxif\bin\SolutionPackagerLib.dll" />
    <Content Include="Daxif\bin\System.Diagnostics.DiagnosticSource.dll" />
    <Content Include="Daxif\bin\System.ValueTuple.dll" />
    <Content Include="Daxif\GenerateXrmMockupMetadata.fsx" />
    <Content Include="XrmContext\FSharp.Core.dll" />
    <Content Include="XrmContext\Microsoft.Crm.Sdk.Proxy.dll" />
    <Content Include="XrmContext\Microsoft.IdentityModel.Clients.ActiveDirectory.dll" />
    <Content Include="XrmContext\Microsoft.IdentityModel.Clients.ActiveDirectory.Platform.dll" />
    <Content Include="XrmContext\Microsoft.Rest.ClientRuntime.dll" />
    <Content Include="XrmContext\Microsoft.Xrm.Sdk.Deployment.dll" />
    <Content Include="XrmContext\Microsoft.Xrm.Sdk.dll" />
    <Content Include="XrmContext\Microsoft.Xrm.Sdk.Workflow.dll" />
    <Content Include="XrmContext\Microsoft.Xrm.Tooling.Connector.dll" />
    <Content Include="XrmContext\Newtonsoft.Json.dll" />
    <Content Include="XrmContext\System.Buffers.dll" />
    <Content Include="XrmContext\System.Memory.dll" />
    <Content Include="XrmContext\System.Numerics.Vectors.dll" />
    <Content Include="XrmContext\System.Runtime.CompilerServices.Unsafe.dll" />
    <Content Include="XrmContext\XrmContext.exe" />
    <Content Include="XrmContext\XrmContext.xml" />
  </ItemGroup>
  <ItemGroup>
    <None Include="XrmContext\XrmContext.exe.config" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Delegate.Daxif" Version="4.8.1" />
    <PackageReference Include="Delegate.XrmContext" Version="1.8.0" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.IdentityModel.Clients.ActiveDirectory" Version="3.19.8" />
    <PackageReference Include="Microsoft.Rest.ClientRuntime" Version="2.3.20" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="System.DirectoryServices" Version="7.0.1" />
    <PackageReference Include="System.DirectoryServices.AccountManagement" Version="7.0.0" />
    <PackageReference Include="System.Runtime.Caching" Version="7.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.ServiceModel.Primitives" Version="6.0.0" />
    <PackageReference Include="System.ServiceModel.Http" Version="6.0.0" />
    <PackageReference Include="System.ServiceModel.Duplex" Version="6.0.0" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="6.0.0" />
    <PackageReference Include="System.ServiceModel.Security" Version="6.0.0" />
    <PackageReference Include="System.ServiceModel.Federation" Version="6.0.0" />
  </ItemGroup>
</Project>